name: Build testing image
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: .github/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.pkg.github.com/lafranceinsoumise/actionpopulaire.fr/agir-test-image:latest
