name: Build front bundles
concurrency:
  group: '${{ github.ref }}'
  cancel-in-progress: true
on: [push]

jobs:
  webpack:
    name: Webpack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-

      - uses: actions/cache@v2
        with:
          path: ~/.babel-cache
          key: babel-${{ hashFiles('agir/**/*.js') }}
          restore-keys: |
            babel-${{ hashFiles('agir/**/*.js') }}
            babel-

      - name: Install node dependencies
        run: npm ci

      - name: Build staging bundles
        run: npm run build
        if: ${{ github.ref != 'refs/heads/production'}}
        env:
          WEBPUSH_PUBLIC_KEY: "${{ secrets.WEBPUSH_PUBLIC_KEY }}"
          SENTRY_ENV: "staging"

      - name: Build production bundles
        run: npm run build
        if: ${{ github.ref == 'refs/heads/production'}}
        env:
          WEBPUSH_PUBLIC_KEY: "${{ secrets.WEBPUSH_PUBLIC_KEY }}"
          SENTRY_ENV: "production"

      - uses: actions/upload-artifact@v2
        with:
          name: assets
          path: assets/

      - name: Tell the team
        run: curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}\&text=Build%20production%20terminé"
        if: ${{ github.ref == 'refs/heads/production'}}

      - name: Tell the team
        run: curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}\&text=Build%20staging%20terminé"
        if: ${{ github.ref == 'refs/heads/staging'}}
